spring:
  profiles:
    active: local

---
server:
  port: 9000

spring:
  config:
    activate:
      on-profiles: local
  kafka:
    consumer:
      bootstrap-servers: kafka:9092
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer