spring:
  profiles:
    active: local

---
server:
  port: 8000

auto:
  create:
    topics:
      enable: true

spring:
  config:
    activate:
      on-profile: local
  kafka:    
    template:
      default-topic: bookstore-events
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer